### ISSUE TITLE
Mind sharing your templates.json file?

### ISSUE THREAD

**Issue by jaanaltosaar** [DanielRunningen/rM2Mods#2]
This is super useful, thank you so much! 

I just can't figure out the right properties to change in the templates.json file - mind sharing your configuration for the excellent templates you've created?

**Comment by DanielRunningen** [comment]
Apologies for the late response, but have you looked through the [templates README](https://github.com/DanielRunningen/rM2Mods/blob/main/assests/templates/README.md)? I tried my best to include what is needed and why when adding to or modifying the `template.json` file, but would be happy to address any specific questions I might have missed. My personal copy is a nightmare that removes most of the original content, so I'm not sure if that would be of much help.

**Comment by jaanaltosaar** [comment]
Sounds good, thank you! There were just too many to try out/add :) 

The sleep ones are beautiful, but unfortunately stopped working after the last update!
